name: generate-changelog
description: generates changelog for current branch
inputs:
  token:
    description: GitHub user's PAT with required permissions
    required: true

  ssh_private_key:
    description: GitHub user's private SSH key part to access to repository
    required: true

  push_event:
    description: GitHub push event that triggers workflow in JSON format
    required: true

  commit_message:
    description: generated changes commit message
    required: false
    default: 'Changelog update'

  standalone:
    description: perform Git operations as standalone operation
    required: false
    default: 'true'

  generator_version:
    description: github-changelog-generator docker image version tag
    required: false
    default: '1.16.1'

  future_release:
    description: future release version
    required: false


runs:
  using: 'node12'
  main: 'dist/main.js'
