name: release-pr-bot
description: release PR bot action
inputs:
  event:
    description: occred PR event
    required: true
  token:
    description: GitHub personal access token to access API
    required: true

runs:
  using: 'node12'
  main: 'dist/main.js'

