name: install-cloud
description: patch and install resolve cloud environment
inputs:
  aws_access_key_id:
    description: aws access key id
    required: true

  aws_secret_access_key:
    description: aws secret aceess key
    required: true

  stage:
    description: cloud stage name (e.g. 'dev', 'prod', 'test')
    required: true

  source:
    description: local path to source files
    required: true

  version:
    description: bump reSolve framework version before building
    required: false

  registry:
    description: package registry to install packages from
    required: false

  token:
    description: package registry authentication token
    required: false

  scopes:
    description: a list of comma separated scopes to map to custom NPM registry
    required: false

  framework_scope:
    description: reSolve framework scope for packages detection
    required: false
    default: '@resolve-js'

outputs:
  api_url:
    description: cloud service API url
  event_store_cluster_arn:
    description: Event Store cluster ARN
  read_models_cluster_arn:
    description: Read Models cluster ARN
  system_cluster_arn:
    description: System cluster ARN
  system_database_name:
    description: System database name
  postgres_admin_username:
    description: Postgres admin username
  postgres_admin_password:
    description: Postgres admin password
  postgres_admin_secret_name:
    description: Postgres admin secret name
  postgres_admin_secret_arn:
    description: Postgres admin secret ARN

runs:
  using: 'node12'
  main: 'dist/main.js'
  post: 'dist/post.js'
