name: install-cloud
description: patch and install resolve cloud environment
inputs:
  aws_access_key_id:
    description: aws access key id
    required: true

  aws_secret_access_key:
    description: aws secret aceess key
    required: true

  stage:
    description: cloud stage name (e.g. 'dev', 'prod', 'test')
    required: true

  source:
    description: local path to source files
    required: true

  version:
    description: bump reSolve framework version before building
    required: false

  registry:
    description: package registry to install packages from
    required: false

  token:
    description: package registry authentication token
    required: false

  scopes:
    description: a list of comma separated scopes to map to custom NPM registry
    required: false

outputs:
  api_url:
    description: cloud service API url

runs:
  using: 'node12'
  main: 'dist/main/index.js'
