name: deploy
description: deploys an appliation to specified cloud environment
inputs:
  directory:
    description: target application directory
    required: true
  cloud_api_url:
    description: reSolve cloud service API url
    required: true
  cloud_user:
    description: reSolve cloud service user
    required: true
  cloud_token:
    description: reSolve cloud service refresh token
    required: true
  name:
    description: override application name
    required: false
    default: ''
  generate_app_name:
    description: automatically generate uniquie app name
    required: false
    default: 'false'
  version:
    description: reSolve framework version override
    required: false
  registry:
    description: packages registry override
    required: false
  deploy_args:
    description: custom resolve-cloud deploy command arguments
    required: false
    default: ''
  local_mode:
    description: action running on developer machine
    required: false
    default: 'false'

outputs:
  id:
    description: deployed application id
  name:
    description: deployed application name
  url:
    description: deployed application url
  runtime:
    description: deployed application runtime version

runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/main/index.js'
