name: deploy
description: deploys an appliation to specified cloud environment
inputs:
  source:
    description: target application directory
    required: true

  cloud_api_url:
    description: reSolve cloud service API url
    required: true

  cloud_user:
    description: reSolve cloud service user
    required: true

  cloud_token:
    description: reSolve cloud service refresh token
    required: true

  name:
    description: override application name
    required: false
    default: ''

  randomize_name:
    description: add random salt to application name postfix
    required: false
    default: 'false'

  framework_version:
    description: reSolve framework version override
    required: false

  registry:
    description: packages registry override
    required: false

  token:
    description: packages registry authentication token
    required: false

  scopes:
    description: a list of comma separated scopes to map to custom NPM registry
    required: false

  deploy_args:
    description: custom resolve-cloud deploy command arguments
    required: false
    default: ''

  cli_version:
    description: use specific cloud CLI version
    required: false

  local_run:
    description: action running on developer machine
    required: false
    default: 'false'

outputs:
  id:
    description: deployed application id
  name:
    description: deployed application name
  url:
    description: deployed application url
  runtime:
    description: deployed application runtime version
  eventstore_id:
    description: deployed application event store identifier

runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/main/index.js'
