name: deploy
description: deploys an appliation to specified cloud environment
inputs:
  source:
    description: target application directory
    required: true

  cloud_user:
    description: reSolve cloud service user
    required: true

  cloud_token:
    description: reSolve cloud service refresh token
    required: true

  cloud_api_url:
    description: reSolve cloud service API url
    required: false

  name:
    description: override application name
    required: false
    default: ''

  randomize_name:
    description: add random salt to application name postfix
    required: false
    default: 'false'

  framework_version:
    description: reSolve framework version override
    required: false

  package_registry:
    description: packages registry override
    required: false

  package_registry_token:
    description: packages registry authentication token
    required: false

  package_registry_scopes:
    description: a list of comma separated scopes to map to custom NPM registry
    required: false

  deploy_args:
    description: custom resolve-cloud deploy command arguments
    required: false
    default: ''

  cli_version:
    description: use specific cloud CLI version
    required: false

  cli_sources:
    description: use cloud CLI sources instead of package
    required: false

  local_run:
    description: action running on developer machine
    required: false
    default: 'false'

  framework_scope:
    description: reSolve framework scope for packages detection
    required: false
    default: '@resolve-js'

  event_store_path:
    description: initial event-store path
    required: false

  skip_remove:
    description: do not remove deployment at the end of the job
    required: false
    default: 'false'

  retrieve_logs:
    description: retrieve deployment logs within action post hook
    required: false
    default: 'false'

outputs:
  id:
    description: deployed application id
  name:
    description: deployed application name
  url:
    description: deployed application url
  runtime:
    description: deployed application runtime version
  event_store_id:
    description: deployed application event store identifier

runs:
  using: 'node12'
  main: 'dist/main.js'
  post: 'dist/post.js'
