name: npm publish
description: publishes packages to specified repository
inputs:
  registry:
    description: NPM registry to publish to
    required: true
  token:
    description: NPM registry authentication token
    required: true
  version:
    description: packages version
    required: true
  build:
    description: build semver part for automatic versioning
    required: false
  tag:
    description: packages tag
    required: false
  unpublish:
    description: automatically unpublish packages on post hook
    required: false
    default: 'false'
  owner:
    description: when registry was set to 'github' this field contains github organization or user
    required: false

outputs:
  registry_url:
    description: registry where package was published
  version:
    description: published packages version
  tag:
    description: published packages tag

runs:
  using: 'node12'
  main: 'dist/main.js'
  post: 'dist/post.js'
