name: npm publish
description: publishes packages to specified repository
inputs:
  registry:
    description: NPM registry to publish to
    required: true
  token:
    description: NPM registry authentication token
    required: true
  version:
    description: packages version (specify 'current' to use version from package.json)
    required: true
  tag:
    description: packages tag
    required: false
  unpublish:
    description: automatically unpublish packages on post hook
    required: false
    default: 'false'

outputs:
  registry_url:
    description: registry where package was published
  version:
    description: published packages version
  tag:
    description: published packages tag

runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
